---
title: "Final Portfolio Week"
format: 
  revealjs:
      theme: [simple, ../style.scss]
      auto-stretch: false
editor: source
execute:
  echo: true
---

# Lab 10 Recap

## Informative Titles

::: {.midi}
Can you incorporate the context of the data into the table? 

- Column names
- Table header
- Table subheader
- Table caption
:::

. . .

::: {.midi}
Can you incorporate the context of the data into the plot? 

- Axis labels
- Plot title
- Plot subtitle 
- Plot caption
:::

## On the handout...

The text in orange indicates learning targets that have been covered **after**
the midterm portfolio was submitted! 


## Modification to Learning Targets

None of the lab assignments had a setting where a `p_map()` or a `map2()` was
needed.

> Change the using a `map()` function with **more than one** input section to 
> a **second** example of using a `map()` function with **one** input!


## Modification to Allowable Assignments

We never read in an `.xlsx` data file for a Lab or Challenge.

> You can use a Practice Activity or Check-in to demonstrate
> this target.

## When locating code...

::: {.midi}
You **must** use unique examples for the following learning targets:

- visualizations (DVS-1),
- `across()` (PE-1, PE-3, DVS-4)
- `map()` (PE-1, PE-3) 
:::

. . .

::: {.midi}
Meaning, all four plots for DVS-1 need to be different! All three examples of
`across()` need to be different, and both examples of `map()` need to be 
different.
:::

. . .

::: {.midi}
All other learning targets can use code included in other locations!
:::

## For example...

::: {.small}
the code below could be used to demonstrate proficiency
with:

- PE-2 (writing functions that operate on vectors)
- R-2 (well documented code)
- DSSM-1 (simulating data)

```{r}
#| echo: true
#| eval: false
#| label: example-student-code
#| code-line-numbers: false

randomBabies <- function(nBabies) {
  # Create a vector representing the parents
  parents <- 1:nBabies
  
  # Shuffle the babies randomly
  babies <- sample(parents)
  
  # Count how many babies are correctly returned
  sum(parents == babies)
}
```
:::

# Determining Your Grade

## Determining Your Grade

> I believe my grade equivalent to course work evidenced below to be an __.

. . .

Your goal is to argue, convincingly and with concrete evidence, that you have
met the criteria for both content proficiency, evidence of continued learning, 
and growth as a team member that goes with a particular grade. 

## On the handout...

- Each grade level has a set of criteria.

- Higher grades build on lower grades.

- You earn a grade only if all criteria for that grade and all lower grades are
satisfied.

- Missing even one required criterion caps your grade at the highest level where
all criteria are met.

<!-- Think of grades as a ladder: you can’t climb to the next grade unless you’ve -->
<!-- stepped on every rung below. -->

<!-- To earn a B → you must complete all B, C, and D criteria. -->

## What if I have met all the criteria for a C and some of the criteria for a B?

This would fall into the bucket of either a C+ or a B-. 

::: columns
::: {.column width="48%"}
::: {.fragment}
**For a C+**

You’ve met all the criteria for a C along with a large
amount, but not all, of the criteria for a B. 
:::
:::

::: {.column width="4%"}
:::

::: {.column width="48%"}
::: {.fragment}
**For an B-** 

You’ve met almost all the requirements for a B, except for a small
number of minor criteria.
:::
:::
:::

## What if we don't agree?

There are two ways this might happen.


::: columns
::: {.column width="48%"}
:::{.fragment}
::: {.small}
***You ask for a grade that is higher than the evidence supports.***

</br>

::: {.fragment}
That is, you grade yourself too highly. For example, you believe you earned an A
in the course, but I do not feel the evidence you’ve provided supports this
grade.

</br>

::: {.fragment}
In this case, I’ll ask you to explain how you would modify a portion of the 
code you've included in your portfolio to be more efficient. 
:::
:::
:::
:::
:::

::: {.column width="4%"}
:::

::: {.column width="48%"}

</br>
</br> 

::: {.small}
::: {.fragment}
If your response communicates that you understand this key concept, I will
take this as evidence in favor of the grade you proposed. 
:::

</br> 
</br> 

::: {.fragment}
If your response communicates that you **do not** understand this key concept, I
will take this as evidence against the grade you proposed. I will award you the
highest grade I believe the evidence in your portfolio supports. 
:::
:::
:::
:::

## What if we don't agree?

::: columns
::: {.column width="40%"}
::: {.small}
***You ask for a grade that was lower than your actual performance indicates.***
:::

</br>

:::{.fragment}
::: {.small}
That is, you "lowball" yourself, for example you say you earned a B+ when in 
fact I think you earned an A-.
:::
:::
:::

::: {.column width="5%"}
:::

::: {.column width="55%"}

</br>
</br>
</br>

::: {.fragment}
::: {.small}
In this case, I will tell you what grade I believe you have earned and why.
:::
:::
:::
:::


# Final Portfolio Meetings

. . .

> Will occur from 9am - 4pm on Saturday, and  
> 9am - 1pm on Monday.

. . .

</br> 

Sign-up for your time here: [link to Google Sheet](https://docs.google.com/spreadsheets/d/1lztEUpTz4kIFohzrVIyRDFjc7ssJG-2M_Qu4TSQZtug/edit?usp=sharing)

::: {.callout-warning}
# The sign-up will close at 5pm on Friday.
:::

## Final Portfolio Deadline

The link to your Final Portfolio repository is due by Friday at 5pm. 

::: {.callout-warning}
# Deadline extensions will not be accepted. 

If you do not submit a Final Portfolio by the deadline, [I will use your Midterm Portfolio as well as completion of assignments from Week 7 - 10 to guide my decision.](https://atheobold.github.io/groupworthy-data-science/portfolio/portfolio-instructions.html#q-what-if-you-do-not-submit-a-final-portfolio)
:::

