---
title: "Working with Dates Using `lubridate`"
format: html
number-sections: true
number-depth: 2
bibliography: references.bib
editor: source
execute: 
  echo: true
  include: true
---

```{r}
#| include: false

library(tidyverse)
library(lubridate)
```

This week is all about special data types in R. Similar to the tools you learned
last week for working with factors, this week you are going to learn about 
tools for working with dates. By the end of this week you should be
able to:

+ Work with date and time variables using `lubridate`

<!-- add more here -->

::: columns
::: {.column width="60%"}
#### 📽 Watch Videos: 20 minutes

#### 📖 Readings: 60-75 minutes

:::

::: {.column width="5%"}
:::

::: {.column width="35%"}
#### ✅   Preview Activities: 1
:::
:::


# Working with Dates {#sec-dates}

In order to fill in an important part of our toolbox, we need to learn how to
work with date variables. These variables feel like they should be simple and
intuitive given we all work with schedules and calendars everyday. However,
there are little nuances that we will learn to make working with dates and times
easier.

::: column-margin
{{< video https://www.youtube.com/embed/SEPjN2AJqbo >}} 
:::

### 📖 [Required Reading: *R4DS* -- Dates and Times](https://r4ds.hadley.nz/datetimes.html)

::: {.callout-tip collapse="true"}
# Extra resources

-   [**lubridate** website](https://lubridate.tidyverse.org/reference/)

-   Download the [**lubridate** cheatsheet](https://posit.co/wp-content/uploads/2022/10/lubridate-1.pdf)

-   [A more in-depth discussion of the POSIXlt and POSIXct data classes.](https://www.cyclismo.org/tutorial/R/time.html)

-   [A tutorial on lubridate](https://data.library.virginia.edu/working-with-dates-and-time-in-r-using-the-lubridate-package/) - scroll down for details on intervals if you have trouble with `%within%` and `%--%`
:::

### ✅   **Check-in 5.2: Functions from `lubridate`**

**Q1** Which of the following is true about the `year()` function?

-   `year()` creates a duration object to be added to a datetime
-   `year()` extracts the year of a datetime object

**Q3** What `tz` would you use for San Luis Obispo? *Use the __exact input__ 
you would use in R!*

**Q3** Which of the following is true about the `%within%` operator?

-   it checks if a date is included in an interval
-   it returns a logical value
-   it creates an interval with a start and end time

**Q4** Which of the following is true about the `%--%` operator?

-   it creates an interval with a start and end time
-   it returns a logical value
-   it checks if a date is included in an interval

**Q5** What day does the `make_date()` function use as default if no `day`
argument is provided?

