---
title: "Week 5 Day 1: Working with Strings"
format: docx
execute: 
  eval: false
---

1.  What inputs do `str_XXXX()` functions require?

2.  Fill in the regular expression table below.

| Regular Expression | Example | What does this expression it mean (in words)? |
|----|----|----|
| `^` | `"^California State"` |  |
| `$` | `"State University$"` |  |
| `+` | `"St\\.+"` |  |
| `*` | `"\\s*-\\s*"` |  |
| `{a}` | `"[A-Z]{4}"` |  |
| `{a,b}` | `"[A-Z]{4,6}"` |  |
| `{a,}` | `"[A-Z]{4,}"` |  |
| `()` | `"(T|t)ech"` |  |
| `|` | `"(T|t)ech"` |  |
| `[A-Z]` | `"[A-Z]{4,}"` |  |
| `[:alnum:]` | `"[:digit:]+"` |  |
| `[:punct:]` | `"[:punct:]{2,}"` |  |
| `[^]` | `"[^University]"` |  |
| `^[^]` | `"^[^University]"` |  |

3.  Fill in the table on `stringr` functions below.

|  |  |  |
|----|----|----|
| Function | **Example** | **What does this function do?** |
| `str_detect(x, pattern = ...)` | `str_detect(my_vector,            pattern = "Bond")` |  |
| `str_replace(x, pattern = ...,  replacement = ...)` | `str_replace(my_vector,             pattern = "Bond",             replace = "Franco")` |  |
| `str_remove(x, pattern = ...)` | `str_remove(my_vector, pattern = "Bond")` |  |
| `str_length()` | `str_length(INSTNM)` |  |
| `str_sub(x, a, b)` | `str_sub(INSTNM, start = 1, end = 8)` |  |
| `str_pad(x, side = ...)` | `str_pad(INSTNM, width = 20, pad = "_")` |  |
| `str_to_lower()` | `str_to_lower(INSTNM)` |  |
| `str_to_upper()` | `str_to_upper(INSTNM)` |  |
| `str_to_title()` | `str_to_title(INSTNM)` |  |
| `str_trim(x)` | `str_to_trim(INSTNM, side = "both")` |  |
